name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 79.143.92.32
          port: 2222
          username: ivan
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html/reddit
            git pull
            npm run build
            sudo service php8.2-fpm restart
